<a href="https://colab.research.google.com/github/chetansolanke14/NaturalLanguageProcessing/blob/master/DeepLearningWithNLP/IRIS_DATATSET_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.datasets import load_iris

In [0]:
iris =load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [0]:
X =iris.data

In [0]:
y =iris.target

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
#class . 0 -->[1,0,0]
#class . 1 -->[0,1,0]
#class . 2 -->[0,0,1]


In [0]:
from keras.utils import to_categorical

In [0]:
y=to_categorical(y)

In [14]:
y.shape

(150, 3)

In [17]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.33,
                                                    random_state=42)

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler = MinMaxScaler()

In [24]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
scaled_x_train=scaler.transform(X_train)

In [0]:
scaled_x_test=scaler.transform(X_test)

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
model =Sequential()

W0618 16:58:55.603253 140129305495424 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [29]:
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])

W0618 17:01:24.459962 140129305495424 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0618 17:01:24.471904 140129305495424 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0618 17:01:24.520656 140129305495424 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0618 17:01:24.546848 140129305495424 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [30]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.fit(scaled_x_train,y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 0.4767 - acc: 0.6700
Epoch 2/150
 - 0s - loss: 0.4763 - acc: 0.6800
Epoch 3/150
 - 0s - loss: 0.4758 - acc: 0.6800
Epoch 4/150
 - 0s - loss: 0.4753 - acc: 0.6800
Epoch 5/150
 - 0s - loss: 0.4747 - acc: 0.6800
Epoch 6/150
 - 0s - loss: 0.4742 - acc: 0.6800
Epoch 7/150
 - 0s - loss: 0.4736 - acc: 0.6800
Epoch 8/150
 - 0s - loss: 0.4726 - acc: 0.6800
Epoch 9/150
 - 0s - loss: 0.4720 - acc: 0.6700
Epoch 10/150
 - 0s - loss: 0.4714 - acc: 0.6700
Epoch 11/150
 - 0s - loss: 0.4708 - acc: 0.6700
Epoch 12/150
 - 0s - loss: 0.4703 - acc: 0.6700
Epoch 13/150
 - 0s - loss: 0.4699 - acc: 0.6700
Epoch 14/150
 - 0s - loss: 0.4695 - acc: 0.6700
Epoch 15/150
 - 0s - loss: 0.4688 - acc: 0.6700
Epoch 16/150
 - 0s - loss: 0.4681 - acc: 0.6700
Epoch 17/150
 - 0s - loss: 0.4678 - acc: 0.6700
Epoch 18/150
 - 0s - loss: 0.4672 - acc: 0.6600
Epoch 19/150
 - 0s - loss: 0.4666 - acc: 0.6600
Epoch 20/150
 - 0s - loss: 0.4661 - acc: 0.6500
Epoch 21/150
 - 0s - loss: 0.4656 - acc: 0.6600
E

In [33]:
model.predict(scaled_x_test)

array([[2.3696225e-03, 4.8627877e-01, 5.1135159e-01],
       [9.9616134e-01, 3.2591445e-03, 5.7950569e-04],
       [2.9950074e-06, 1.5729626e-01, 8.4270072e-01],
       [2.8097059e-03, 5.1697260e-01, 4.8021778e-01],
       [5.3645583e-04, 3.9494267e-01, 6.0452092e-01],
       [9.9314708e-01, 5.7919039e-03, 1.0610635e-03],
       [1.8566156e-02, 6.4458448e-01, 3.3684939e-01],
       [1.5853583e-04, 3.5593262e-01, 6.4390886e-01],
       [7.8113057e-04, 4.0476784e-01, 5.9445095e-01],
       [8.5002873e-03, 5.8212650e-01, 4.0937319e-01],
       [5.0526916e-04, 4.2164671e-01, 5.7784808e-01],
       [9.9195248e-01, 6.6650575e-03, 1.3825190e-03],
       [9.9675888e-01, 2.7495723e-03, 4.9152196e-04],
       [9.9277014e-01, 6.0100183e-03, 1.2198378e-03],
       [9.9788254e-01, 1.7939656e-03, 3.2343174e-04],
       [2.1009957e-03, 5.1365095e-01, 4.8424804e-01],
       [1.2349128e-04, 3.2205492e-01, 6.7782158e-01],
       [1.0011322e-02, 5.8045781e-01, 4.0953088e-01],
       [4.9839634e-03, 5.432

In [34]:
model.predict_classes(scaled_x_test)

array([2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

In [0]:
prediction =model.predict_classes(scaled_x_test)

In [36]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [0]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
confusion_matrix(y_test.argmax(axis=1), prediction)

array([[19,  0,  0],
       [ 0,  9,  6],
       [ 0,  0, 16]])

In [39]:
print(classification_report(y_test.argmax(axis=1), prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.60      0.75        15
           2       0.73      1.00      0.84        16

    accuracy                           0.88        50
   macro avg       0.91      0.87      0.86        50
weighted avg       0.91      0.88      0.87        50



In [0]:
model.save('myfirstmodel.h5')

In [0]:
from keras.models import load_model

In [0]:
new_model =load_model('myfirstmodel.h5')

In [43]:
new_model.predict_classes(scaled_x_test)

array([2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])