<a href="https://colab.research.google.com/github/chetansolanke14/NaturalLanguageProcessing/blob/master/DeepLearningWithNLP/TextGeneration_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#1 Process Text
#2 CleanText
#3 Tokenize Text

In [0]:
def read_file(filepath):
  with open(filepath) as f:
    str_text =f.read()
    
  return str_text

In [0]:
#read_moby dick four chapter

In [0]:
import spacy

In [0]:
nlp =spacy.load('en',disable=['parser','tagger','ner'])

In [0]:
nlp.max_length= 1198623 #totalword in moby ick book

In [0]:
def saperate_punc(doc_text):
  return[token.text.lower() for token in nlp(doc_text) 
        if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [0]:
d =read_file('moby_dick_four_chapters.txt')

In [0]:
tokens =saperate_punc(d)

In [18]:
len(tokens)

11338

In [0]:
#pass 25 words and have network to predict word number 26

In [0]:
train_len=25+1

text_sqequences=[]

for i in range(train_len, len(tokens)):
  seq =tokens[i-train_len:i]
  
  text_sqequences.append(seq)

In [21]:
type(text_sqequences)

list

In [22]:
' '.join(text_sqequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [23]:
' '.join(text_sqequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [24]:
' '.join(text_sqequences[2])

'ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i'

In [25]:
' '.join(text_sqequences[3])

'some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought'

In [26]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
tokenizer =Tokenizer()

In [0]:
tokenizer.fit_on_texts(text_sqequences)

In [0]:
sequences =tokenizer.texts_to_sequences(text_sqequences)

In [30]:
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 315,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2712,
 14,
 24]

In [31]:
for i in sequences[0]:
  print(f"{i} :{tokenizer.index_word[i]}")

956 :call
14 :me
263 :ishmael
51 :some
261 :years
408 :ago
87 :never
219 :mind
129 :how
111 :long
954 :precisely
260 :having
50 :little
43 :or
38 :no
315 :money
7 :in
23 :my
546 :purse
3 :and
150 :nothing
259 :particular
6 :to
2712 :interest
14 :me
24 :on


In [0]:
#tokenizer.word_counts

In [0]:
vocabulary_size =len(tokenizer.word_counts)

In [34]:
vocabulary_size

2717

In [35]:
type(sequences)

list

In [0]:
import numpy as np

In [0]:
sequences=np.array(sequences)

In [38]:
sequences.shape

(11312, 26)

In [39]:
'''
CREATE LSTM based model
split data into features and labels
fit the model
'''

'\nCREATE LSTM based model\nsplit data into features and labels\nfit the model\n'

In [0]:
from keras.utils import to_categorical

In [41]:
sequences[:,:-1]

array([[ 956,   14,  263, ...,    6, 2712,   14],
       [  14,  263,   51, ..., 2712,   14,   24],
       [ 263,   51,  261, ...,   14,   24,  957],
       ...,
       [ 952,   12,  166, ...,   11,  262,   53],
       [  12,  166, 2711, ...,  262,   53,    2],
       [ 166, 2711,    3, ...,   53,    2, 2717]])

In [42]:
sequences

array([[ 956,   14,  263, ..., 2712,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2711, ...,   53,    2, 2717],
       [ 166, 2711,    3, ...,    2, 2717,   26]])

In [43]:
sequences[:,-1]

array([  24,  957,    5, ...,    2, 2717,   26])

In [0]:
X =sequences[:,:-1]
y=sequences[:,-1]

In [0]:
y =to_categorical(y,num_classes=vocabulary_size+1)

In [0]:
seq_len =X.shape[1]

In [47]:
X.shape

(11312, 25)

In [0]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [0]:
def create_model(vocabulary_size,seq_len):
  
  model=Sequential()
  model.add(Embedding(vocabulary_size,seq_len,input_length=seq_len))
  model.add(LSTM(50,return_sequences=True))
  model.add(LSTM(50))
  model.add(Dense(50,activation='relu'))
  
  model.add(Dense(vocabulary_size,activation='softmax'))
  
  model.compile(loss='categorical_crossentropy',
                optimizer='adam', metrics=['accuracy'])
  model.summary()
  return model

In [50]:
model=create_model(vocabulary_size+1,seq_len)

W0618 18:31:23.027662 139943550044032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0618 18:31:23.074262 139943550044032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0618 18:31:23.084087 139943550044032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0618 18:31:23.533147 139943550044032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0618 18:31:23.556236 139943550044032 deprecation_wrappe

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 25)            67950     
_________________________________________________________________
lstm_1 (LSTM)                (None, 25, 50)            15200     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 2718)              138618    
Total params: 244,518
Trainable params: 244,518
Non-trainable params: 0
_________________________________________________________________


In [0]:
from pickle import dump,load

In [52]:
model.fit(X,y,batch_size=128,epochs=50,verbose=1)

W0618 18:31:23.874579 139943550044032 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0618 18:31:25.166618 139943550044032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
11312/11312 [==============================] - 16s 1ms/step - loss: 6.9891 - acc: 0.0429
Epoch 2/50
11312/11312 [==============================] - 7s 605us/step - loss: 6.3755 - acc: 0.0529
Epoch 3/50
11312/11312 [==============================] - 7s 610us/step - loss: 6.3469 - acc: 0.0529
Epoch 4/50
11312/11312 [==============================] - 7s 604us/step - loss: 6.3367 - acc: 0.0529
Epoch 5/50
11312/11312 [==============================] - 7s 601us/step - loss: 6.3205 - acc: 0.0529
Epoch 6/50
11312/11312 [==============================] - 7s 600us/step - loss: 6.2262 - acc: 0.0529
Epoch 7/50
11312/11312 [==============================] - 7s 603us/step - loss: 6.1044 - acc: 0.0534
Epoch 8/50
11312/11312 [==============================] - 7s 600us/step - loss: 6.0010 - acc: 0.0543
Epoch 9/50
11312/11312 [==============================] - 7s 602us/step - loss: 5.9347 - acc: 0.0545
Epoch 10/50
11312/11312 [==============================] - 7s 596us/step - loss: 5.8811 - ac

In [0]:
model.save('my_mobydick_model.h5')

In [0]:
dump(tokenizer,open('my_simpletokenizer','wb'))

In [0]:
#Generate new text based off of a seed input

In [0]:
from keras.preprocessing.sequence import pad_sequences

In [0]:
def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
  output_text=[]
  
  input_text=seed_text
  
  for i in range(num_gen_words):
    encoded_text=tokenizer.texts_to_sequences([input_text])[0]
    
    pad_encoded =pad_sequences([encoded_text], maxlen=seq_len,
                              truncating='pre')
    
    pred_word_ind=model.predict_classes(pad_encoded,verbose=0)[0]
    
    pred_word=tokenizer.index_word[pred_word_ind]
    
    input_text+= ' '+pred_word
    
    output_text.append(pred_word)
  
  return ' '.join(output_text)

In [58]:
text_sqequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [0]:
import random
random.seed(101)
random_pick=random.randint(0,len(text_sqequences))

In [0]:
random_seed_text=text_sqequences[random_pick]

In [61]:
random_seed_text

['thought',
 'i',
 'to',
 'myself',
 'the',
 'man',
 "'s",
 'a',
 'human',
 'being',
 'just',
 'as',
 'i',
 'am',
 'he',
 'has',
 'just',
 'as',
 'much',
 'reason',
 'to',
 'fear',
 'me',
 'as',
 'i',
 'have']

In [0]:
seed_text=' '.join(random_seed_text)

In [63]:
seed_text

"thought i to myself the man 's a human being just as i am he has just as much reason to fear me as i have"

In [64]:
generate_text(model,tokenizer,seq_len,seed_text,num_gen_words=25)

'not be be be be be be be be be be be be be be be be be be be be be be be be'