<a href="https://colab.research.google.com/github/chetansolanke14/NaturalLanguageProcessing/blob/master/Pycon/Part_1_Primer_on_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1 - Primer on Tensors for Deep Learning using PyTorch

**Required Time: 20 minutes**

In this notebook, we will cover the basic tensor operations which are useful when implementing and training deep learning models. This guide should provide you with enough background on some of the most important tensor operations and computations used in deep learning and machine learning. This will form the foundation for implementing your NLP models. The focus of this notebook will be on use of PyTorch's high-level APIs, but it will provide insights and concise details where necessary to help the reader. 


After completing this guide, and with enough practise, the learner should feel comfortable with basic tensor creation/manipulation, and composing a pipeline of tensor operations, which will become useful when implimenting deep learning models with PyTorch.

---

### Journey
- What is a tensor?
- Building Tensors
- Special Tensors
- Tensor Properties
- Tensor Slicing
- Tensor operations and transformations
- Cuda Tensors
- Pipeline of Tensor Operations

### What is a Tensor?
In different fields and studies, tensors mean completely different things. In the deep learning world, tensors are just high-dimensional data structures which allow for efficient storage and operations. Why are they important? Well, when we are dealing with different kinds of data, such as text and images, we need to *numericalize* (convert to numbers) the data. This means our data will eventually need to be converted into numerical format using some conversion technique. That's not important here. The important part is that tensors store data and we need to learn some properties and chacteristics of them before understanding their use and applicability. 

In [0]:
# Let's important pytorch -- the main PyTorch library;
# already installed for us on the Colab environment
import torch

### Building Tensors
In deep learning, we are mostly dealing with Tensors. Therefore, it's important to understand different concepts about tensors, such as types, size, special tensors, etc. Let's briefly review a few concepts related to building tensors. Pay close attention to the comments.  

In [4]:
# a scalar
A = torch.tensor(1)
print(A)

tensor(1)


In [5]:
# a vector (1D tensor); 3-dimensional vector
A = torch.tensor([1,2,3])
print(A)

tensor([1, 2, 3])


In [6]:
# a matrix (2D tensor)
A = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(A)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
# a matrix (3D tensor)
A = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                  [[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                 ])
print(A)
print(A.size())

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])
torch.Size([2, 2, 4])


In [8]:
# build tensor from a numpy array; useful for data transformations
import numpy as np
A = torch.tensor(np.random.rand(1, 3))
print(A)

tensor([[0.9479, 0.8378, 0.7038]], dtype=torch.float64)


----

### Exercise - Constructing Tensor

Build a PyTorch tensor usiong a list from 1-10. Hint: use `range(...)`.

----

In [9]:
### YOUR CODE HERE

A = torch.arange(1,10)

### YOUR CODE HERE
A

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Special Tensors

We can also build special tensors such as all-zeros matrix, all-ones matrix, already offered by PyTorch.

In [10]:
# builing tensor with zeros
A = torch.zeros(5, 4, dtype=torch.long)
print(A)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [11]:
# All-ones matrix
A = torch.ones(5, 4)
print(A)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
# diagonal matrix
A = torch.eye(5, 5)
print(A)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [13]:
# building tensors with random information
A = torch.rand(5, 4)
print(A)

tensor([[0.3062, 0.9231, 0.8084, 0.7766],
        [0.8456, 0.4103, 0.7324, 0.7801],
        [0.9589, 0.9314, 0.9966, 0.4230],
        [0.7935, 0.9238, 0.4369, 0.8128],
        [0.8170, 0.9098, 0.9080, 0.8604]])


In [14]:
# like another tensor
A = torch.rand(5, 4)

B = torch.ones_like(A)
print(B)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
# 1-dimensional ranges

torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

----

### Exercise - Constructing Tensor

It's important to familiarize oneself with the [PyTorch documentation](https://pytorch.org/docs/stable/torch.html). To make this obvious, let try to construct a tensor tensor with the list of numbers from 1-10. There is an easy way: use `linspace(...)` shown above.

----

In [16]:
### YOUR CODE HERE

A =torch.linspace(1,10)

### YOUR CODE HERE
A

tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

### Tensor Properties
We can check different properties of the tensors we are building. These special functions are helpful to observe the properties of the tensor data structure we are operating on.

In [18]:
# type
A = torch.randn(size = (2,3), dtype = torch.float32)
print(A.type())
A

torch.FloatTensor


tensor([[ 0.9275, -0.1180,  0.1415],
        [ 1.1203,  0.1308,  1.9672]])

In [19]:
# size and view and their difference
A = torch.eye(4,5)
A.size()

torch.Size([4, 5])

The best way to learn and memorize all these properties is to go into the documentation and practice as much as you can. 

### Tensor Slicing
Understanding how to query and slice tensors.

In [20]:
A =  torch.eye(5, 5)

print(A[3:]) # specific row, all columns
print("\n")
print(A[: 3]) # slice of rows, all columns
print("\n")
print(A[: -1]) # from first row to second to last row

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


### Tensor Operations and Transformations

Times, 
element-wise multiplication,
to.tensor() etc...

In [21]:
# modify tensor content
A = torch.ones(5, 4)

A[:2] = 0
print(A)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
# transpose
A.transpose(1,0)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

What happens if we print A again, woud it be transposed?

In [23]:
print(A)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Apparently not! There is a quick fix to make transformations and operations in place. Use "`_`" after the method.

In [24]:
A.transpose_(1, 0)
print(A)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])


Let's do some simple math...

In [25]:
# addition
A = torch.ones(5, 3)
B = torch.ones(5, 3)
print(A + B)

# addition in place
print(torch.add(A, B))

# addition in place; uses symbol "_"
A.add_(B)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [26]:
# power and sum
A =  torch.tensor([1.0, 2.0])
out = A.pow(2).sum()
print(out)

tensor(5.)


In [27]:
# element-wise multiplication

A = torch.eye(5, 5)
B = torch.ones(5, 5)

print(A * B)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


---

### EXERCISE - Tensor Operations and Transformations

Generate this matrix (Hint: `torch.rot90()`):

```python

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])
```

----




In [31]:
A = torch.eye(5, 5)
B = torch.ones(5, 5)
C = A * B

### YOUR CODE HERE
D=C.rot90()

### YOUR CODE HERE
D

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

### Cuda Tensors
PyTorch provides the option to easily manipulate tensors in addition to moving them from gpu and cpu, which allows for ease of training and controlling which parts should be commited to the gpu or the cpu. This gives the control/flexibility to the programmer to design the models for different scenarios with different compute resources.

In [32]:
# check if cuda is available in your computer
print("---------------------------------------------------")
print("Cuda status:", torch.cuda.is_available())

device_0 = torch.device("cuda")
device_1 = torch.device("cpu")

print("---------------------------------------------------")

x = torch.rand(2, 3)
y = torch.ones_like(x, device=device_0)
z = torch.zeros_like(x, device=device_1)
print("Tensor y is stored in: ", y.device)
print(y)
print("---------------------------------------------------")
print("Tensor x is stored in: ", x.device)
print(x)

---------------------------------------------------
Cuda status: True
---------------------------------------------------
Tensor y is stored in:  cuda:0
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
---------------------------------------------------
Tensor x is stored in:  cpu
tensor([[0.3491, 0.8053, 0.1612],
        [0.2456, 0.7837, 0.8778]])


In [35]:
# check if tensor stored in GPU

print(y.is_cuda)
print(x.is_cuda)

True
False


There are significant differences in execution time when dealing with huge tensors.

In [36]:
%%time
a = torch.rand(1000, 1000)
b = torch.rand(1000, 1000)

a.matmul(b)

CPU times: user 40.7 ms, sys: 2.24 ms, total: 43 ms
Wall time: 45.2 ms


In [37]:
%%time
a = torch.rand(1000, 1000).cuda()
b = torch.rand(1000, 1000).cuda()

a.matmul(b)

CPU times: user 18.7 ms, sys: 992 µs, total: 19.6 ms
Wall time: 29.3 ms


### Pipeline of Tensor Operations
With PyTorch everything is a chain of operations  and the high-level APIs offer all the necessary functionalities to achieve this. Below, we will explore a simple approach to chaining tensor operations. In other words, we are designing a graph or a flow of operations that are chained together, designed to output something. This is essential for training neural networks. This is why neural networks are sometimes called **computation graphs**, because they are simply a chain of operations.

In [0]:
import torch.nn as nn

class Chain(nn.Module):
  def __init__(self, ):
    super(Chain, self).__init__()
    
  def forward(self, x):
    print("---------------------------------------------------")
    print("X:")
    print(x)
    print("---------------------------------------------------")
    print("X powered by 2:")
    print(x.pow(2))
    print("mean(X): ")
    out = x.mean()
    return out

In [39]:
x =  torch.rand((4,5), dtype=torch.float64)
chain = Chain()
mean_x = chain(x)
print(mean_x)

---------------------------------------------------
X:
tensor([[0.8438, 0.6458, 0.1362, 0.3858, 0.5754],
        [0.7742, 0.8435, 0.2735, 0.1725, 0.3947],
        [0.9314, 0.4718, 0.1461, 0.7349, 0.8739],
        [0.8958, 0.7001, 0.5050, 0.1199, 0.7704]], dtype=torch.float64)
---------------------------------------------------
X powered by 2:
tensor([[0.7119, 0.4171, 0.0185, 0.1488, 0.3311],
        [0.5994, 0.7114, 0.0748, 0.0298, 0.1558],
        [0.8675, 0.2226, 0.0213, 0.5401, 0.7636],
        [0.8025, 0.4901, 0.2551, 0.0144, 0.5935]], dtype=torch.float64)
mean(X): 
tensor(0.5597, dtype=torch.float64)


The benefit of the chainer or computation graph is that it can resused and different inputs can be fed into it.

In [40]:
y = torch.eye(5,5)
print(torch.mean(y))
chain_2 = Chain()
mean_y = chain_2(y)
print(mean_y)

tensor(0.2000)
---------------------------------------------------
X:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
---------------------------------------------------
X powered by 2:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
mean(X): 
tensor(0.2000)


---

### References
- [GitHub repo](https://github.com/omarsar/nlp_pycon)
- [PyTorch official documentation](https://pytorch.org/docs/stable/tensors.html)
- [A Simple Neural Network from Scratch with PyTorch and Google Colab](https://medium.com/dair-ai/a-simple-neural-network-from-scratch-with-pytorch-and-google-colab-c7f3830618e0)
- [Deep Learning Emotion Recognition with PyTorch](https://github.com/omarsar/appworks_meetup_2018/blob/master/Deep%20Learning%20Emotion%20Recognition%20PyTorch.ipynb)
- [Hacking Neural Networks](https://colab.research.google.com/drive/1Loc882hPQwhq212TS4bpUYsTF7KZUD9x#scrollTo=xeRo4GLruC72)